name: whizapp
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.2
  get: ^4.6.5
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0
  firebase_auth: ^4.2.9
  firebase_core: ^2.7.0
  cloud_firestore: ^4.4.3

  yt_player:
    path: ../yt_player_flutter
  dartz: ^0.10.1
  youtube_player_flutter: ^8.1.2
  flutter_cached_pdfview: ^0.4.1




  
 
 

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/

  
